HTML = r'''<!doctype html><html lang="da"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ChromaLearn AI</title>
<style>
:root{font-family:system-ui,sans-serif;color-scheme:light dark}body{margin:0;background:#f3f5f7;color:#18222d}header{background:#132238;color:#fff;padding:16px 22px}.wrap{max-width:1100px;margin:20px auto;padding:0 15px}.card{background:#fff;border:1px solid #d8dfe6;border-radius:12px;padding:16px;margin:12px 0}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}label{display:block;font-weight:650;margin:9px 0 4px}input,textarea,select,button{font:inherit}input,textarea,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #b9c4ce;border-radius:7px;background:#fff;color:#18222d}textarea{min-height:90px}button{background:#173f70;color:white;border:0;border-radius:7px;padding:9px 13px;font-weight:650;cursor:pointer;margin:3px}.secondary{background:#586575}.danger{background:#8a2630}.tabs button{background:#34495e}.msg{padding:10px;border-radius:8px;margin:8px 0;white-space:pre-wrap}.student{background:#e7f0fa;margin-left:12%}.tutor{background:#edf0f2;margin-right:12%}.muted{opacity:.72;font-size:.9rem}.pill{padding:3px 7px;border-radius:999px;background:#e4e9ee;font-size:.85rem}.hidden{display:none!important}.notice{background:#fff5cf;padding:9px;border-radius:7px}.good{background:#ddf3e4;padding:9px;border-radius:7px}.bad{background:#f8dfe2;padding:9px;border-radius:7px}table{width:100%;border-collapse:collapse}td,th{padding:7px;border-bottom:1px solid #dbe1e6;text-align:left}.modalities{display:flex;flex-wrap:wrap;gap:4px;margin:8px 0}.modality.active{outline:3px solid #8fb3da}.score{font-weight:700}@media(prefers-color-scheme:dark){body{background:#10151a;color:#e9eef3}.card{background:#18212a;border-color:#36424e}input,textarea,select{background:#10161c;color:#eef;border-color:#4d5b68}.student{background:#173651}.tutor{background:#29323a}.pill{background:#323d47}.notice{background:#3a3012}.good{background:#173722}.bad{background:#421f25}}@media(max-width:650px){.row{grid-template-columns:1fr}.student,.tutor{margin:8px 0}}
</style></head><body><header><b>ChromaLearn AI</b> <span class="pill" id="rolePill">…</span><div class="muted" id="school"></div></header><div class="wrap">
<div class="tabs"><button onclick="showTab('learn')">Læring</button><button id="teacherTab" class="hidden" onclick="showTab('teacher')">Lærer</button><button id="adminTab" class="hidden" onclick="showTab('admin')">IT-admin</button><button onclick="showTab('about')">Om</button></div>
<section id="learn" class="card"><h2>Læringsforløb</h2><p class="notice"><b>Sessionsbaseret:</b> Dine svar, læringsmålinger og den adaptive profil findes kun under denne session og nulstilles, når sessionen afsluttes, udløber eller programmet lukkes. Næste session starter forfra.</p><div class="row"><div><label>Profil</label><select id="profile"></select></div><div><label>Emne</label><input id="topic" placeholder="fx ligninger, brøker, grammatik"></div></div><label>Opgave</label><textarea id="task" placeholder="Indsæt eller beskriv opgaven"></textarea><button onclick="start()">Start</button><div id="session" class="hidden"><p>Trin: <span class="pill" id="stage"></span></p><p id="recommendation" class="muted"></p><div id="modalityButtons" class="modalities"></div><div id="chat"></div><button id="speakBtn" class="secondary" onclick="speakLast()">🔊 Læs sidste AI-svar højt</button><label>Dit eget arbejde / din forklaring</label><textarea id="message"></textarea><button onclick="send(false)">Få vejledning</button><button class="secondary" onclick="send(true)">Jeg har prøvet – næste trin</button><button class="secondary" onclick="checkpoint()">Test min forståelse</button><button class="danger" onclick="endSession()">Afslut og nulstil session</button><div id="checkpointBox" class="hidden"><h3>Forståelsestest</h3><p id="checkpointQuestion"></p><textarea id="checkpointAnswer" placeholder="Svar uden hjælp"></textarea><button onclick="gradeCheckpoint()">Vurder min forståelse</button><div id="checkpointResult"></div></div></div></section>
<section id="teacher" class="card hidden"><h2>Lærermodul</h2><p class="muted">Profiler styrer fag, niveau, hjælp, vurderingssituation og tilladte undervisningsformer. Elever kan ikke ændre reglerne.</p><div id="profiles"></div><h3>Opret / redigér profil</h3><div class="row"><div><label>ID</label><input id="pid" placeholder="matematik-7"></div><div><label>Navn</label><input id="pname"></div><div><label>Fag</label><input id="psubject"></div><div><label>Niveau</label><input id="plevel"></div><div><label>Hjælpeniveau 1-4</label><select id="phelp"><option>1</option><option selected>2</option><option>3</option><option>4</option></select></div><div><label>Opgavetype</label><select id="pmode"><option value="practice">Træning</option><option value="homework">Lektie</option><option value="assignment">Aflevering</option><option value="exam">Prøve/eksamen</option></select></div></div><label>Tilladte undervisningsformer</label><label><input class="pmod" type="checkbox" value="text" checked style="width:auto"> Tekst</label><label><input class="pmod" type="checkbox" value="visual" checked style="width:auto"> Visuel struktur/diagram</label><label><input class="pmod" type="checkbox" value="audio" checked style="width:auto"> Lyd/op­læsning</label><label><input class="pmod" type="checkbox" value="activity" checked style="width:auto"> Aktivitet/praktisk øvelse</label><label>Kildepolitik</label><textarea id="psource">Brug opgavens materiale og almindeligt etableret viden. Opfind ikke kilder eller citater.</textarea><label><input id="pexamples" type="checkbox" checked style="width:auto"> Analoge eksempler tilladt</label><label><input id="penabled" type="checkbox" checked style="width:auto"> Profil aktiv</label><br><button onclick="saveProfile()">Gem profil</button></section>
<section id="admin" class="card hidden"><h2>IT-administrator</h2><p class="muted">AI-model og server vælges af skolen. ChromaLearn kræver kun et OpenAI-kompatibelt chat-completions endpoint.</p><div class="row"><div><label>Skolens navn</label><input id="schoolName"></div><div><label>Modelnavn</label><input id="model"></div></div><label>OpenAI-kompatibelt endpoint</label><input id="apiUrl"><div class="row"><div><label>Autentifikation</label><select id="authMode"><option value="none">Ingen</option><option value="bearer_env">Bearer-token fra miljøvariabel</option></select></div><div><label>Miljøvariabel for token</label><input id="apiKeyEnv"></div></div><div class="row"><div><label>AI-request timeout (sek.)</label><input id="timeout" type="number"></div><div><label>Max tokens</label><input id="maxTokens" type="number"></div><div><label>Session idle-timeout (min.)</label><input id="idleTimeout" type="number" min="1" max="120"></div><div><label>Absolut sessionsgrænse (min.)</label><input id="absoluteTimeout" type="number" min="5" max="240"></div></div><label><input id="adaptiveEnabled" type="checkbox" style="width:auto" checked> Adaptiv fag-/emneprofil aktiv</label><label><input id="sessionOnly" type="checkbox" style="width:auto" checked disabled> Adaptive læringsdata er tvungent sessionsbaserede</label><label><input id="persist" type="checkbox" style="width:auto"> Gem elevsamtaler</label><p class="notice">Elevsamtaler og adaptive elevdata er fail-closed og kan ikke gøres permanente i v0.4. Ingen elevspecifik eksport-API findes.</p><button onclick="saveAdmin()">Gem serverkonfiguration</button><button class="secondary" onclick="testBackend()">Test AI-server</button><div id="adminResult"></div></section>
<section id="about" class="card hidden"><h2>Om ChromaLearn</h2><p>Open-source pædagogisk AI-lag. Roller bestemmes af Linux-grupper, ikke af browseren. Den adaptive profil måler læringsudbytte pr. fag/emne kun i den aktive session; den klassificerer ikke elever i faste “læringsstile”, og den gemmes ikke mellem sessioner.</p><p>Lyd bruger browserens lokale tekst-til-tale. Visuel tilstand bruger tabeller, diagrammer og tekstbaserede visualiseringer fra den valgte model. Eksterne billedgeneratorer er ikke en skjult afhængighed.</p><p>Udviklerkilde installeres i <code>/usr/share/chromalearn/developer-repo</code>. Kør <code>chromalearn-export-source</code> for at kopiere det komplette Git-repository til din hjemmemappe.</p></section>
</div><script>
let meta={},sid=null,lastTutor='',currentModality='text'; const names={attempt:'Første forsøg',diagnose:'Find problemet',hint:'Hint',reflect:'Forklar hvorfor',consolidate:'Saml læringen'}; const modNames={text:'Tekst',visual:'Visuelt',audio:'Lyd',activity:'Aktivitet'};
async function req(url,opt={}){let r=await fetch(url,opt);let j=await r.json();if(!r.ok)throw Error(j.error||'Fejl');return j}function showTab(id){for(const x of ['learn','teacher','admin','about'])document.getElementById(x).classList.toggle('hidden',x!==id)}
function add(role,text){let d=document.createElement('div');d.className='msg '+(role==='student'?'student':'tutor');d.textContent=(role==='student'?'Dig: ':'ChromaLearn: ')+text;chat.appendChild(d);if(role==='tutor')lastTutor=text}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function boot(){meta=await req('/api/meta');rolePill.textContent=meta.role;school.textContent=meta.school_name||'';teacherTab.classList.toggle('hidden',!['teacher','admin'].includes(meta.role));adminTab.classList.toggle('hidden',meta.role!=='admin');await loadProfiles();if(meta.role==='admin')await loadAdmin()}
async function loadProfiles(){let j=await req('/api/profiles');profile.innerHTML='';for(const p of j.profiles){let o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+p.subject+' · '+p.level;profile.appendChild(o)}if(['teacher','admin'].includes(meta.role)){profiles.innerHTML='<table><tr><th>ID</th><th>Navn</th><th>Fag/niveau</th><th>Hjælp</th><th>Former</th><th></th></tr>'+j.profiles_all.map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.name)}</td><td>${esc(p.subject)} / ${esc(p.level)}</td><td>${p.help_level}</td><td>${esc((p.modalities||[]).join(', '))}</td><td><button class="secondary" onclick='editProfile(${JSON.stringify(JSON.stringify(p))})'>Redigér</button>${p.id==='default'?'':`<button class="danger" onclick='delProfile(${JSON.stringify(p.id)})'>Slet</button>`}</td></tr>`).join('')+'</table>'}}
function editProfile(raw){let p=JSON.parse(raw);pid.value=p.id;pname.value=p.name;psubject.value=p.subject;plevel.value=p.level;phelp.value=p.help_level;pmode.value=p.assessment_mode;psource.value=p.source_policy;pexamples.checked=p.allow_analogous_examples;penabled.checked=p.enabled;document.querySelectorAll('.pmod').forEach(x=>x.checked=(p.modalities||['text']).includes(x.value))}
async function saveProfile(){let mods=[...document.querySelectorAll('.pmod:checked')].map(x=>x.value);let p={id:pid.value,name:pname.value,subject:psubject.value,level:plevel.value,help_level:+phelp.value,assessment_mode:pmode.value,source_policy:psource.value,allow_analogous_examples:pexamples.checked,enabled:penabled.checked,modalities:mods};await req('/api/profiles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});await loadProfiles();alert('Profil gemt')}
async function delProfile(id){if(confirm('Slet profil '+id+'?')){await req('/api/profiles/'+encodeURIComponent(id),{method:'DELETE'});await loadProfiles()}}
function setModality(m){currentModality=m;document.querySelectorAll('.modality').forEach(b=>b.classList.toggle('active',b.dataset.m===m))}
function renderModalities(mods){modalityButtons.innerHTML='';for(const m of mods){let b=document.createElement('button');b.className='secondary modality';b.dataset.m=m;b.textContent=modNames[m]||m;b.onclick=()=>setModality(m);modalityButtons.appendChild(b)}setModality(currentModality)}
async function start(){if(sid)await endSession(false);if(!task.value.trim())return alert('Skriv en opgave');let j=await req('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile_id:profile.value,task:task.value,topic:topic.value||'general'})});sid=j.session_id;currentModality=j.modality;session.classList.remove('hidden');stage.textContent=names[j.stage];chat.innerHTML='';checkpointBox.classList.add('hidden');recommendation.textContent=j.recommendation.reason;renderModalities(j.modalities);add('tutor',j.opening)}
async function send(advance){if(!message.value.trim())return alert('Skriv dit eget forsøg først');let t=message.value;message.value='';add('student',t);let j=await req('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,message:t,advance,modality:currentModality})});stage.textContent=names[j.stage]||j.stage;add('tutor',j.reply);if(currentModality==='audio')speakLast()}
function speakLast(){if(!lastTutor)return;if(!('speechSynthesis' in window))return alert('Tekst-til-tale understøttes ikke af denne browser.');speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(lastTutor);u.lang='da-DK';speechSynthesis.speak(u)}
async function endSession(show=true){if(!sid){if(show)alert('Ingen aktiv session');return;}try{await req('/api/session/end',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid})})}catch(e){}sid=null;lastTutor='';chat.innerHTML='';message.value='';checkpointAnswer.value='';checkpointBox.classList.add('hidden');session.classList.add('hidden');if('speechSynthesis' in window)speechSynthesis.cancel();if(show)alert('Sessionen er afsluttet og nulstillet. Næste session starter uden denne elevprofil.')}
async function checkpoint(){if(!sid)return alert('Start først et læringsforløb');checkpointResult.innerHTML='';checkpointAnswer.value='';let j=await req('/api/checkpoint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid})});checkpointQuestion.textContent=j.question;checkpointBox.classList.remove('hidden')}
async function gradeCheckpoint(){if(!checkpointAnswer.value.trim())return alert('Skriv dit svar først');let j=await req('/api/checkpoint/grade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sid,answer:checkpointAnswer.value})});checkpointResult.innerHTML='<p class="'+(j.score===2?'good':j.score===1?'notice':'bad')+'"><span class="score">Score '+j.score+'/2.</span> '+esc(j.feedback)+'</p><p class="muted">'+esc(j.recommendation.reason)+'</p>';recommendation.textContent=j.recommendation.reason;currentModality=j.recommendation.modality;setModality(currentModality)}
async function loadAdmin(){let c=(await req('/api/admin/config')).config;schoolName.value=c.school_name||'';model.value=c.model||'';apiUrl.value=c.api_url||'';authMode.value=c.auth_mode||'none';apiKeyEnv.value=c.api_key_env||'';timeout.value=c.request_timeout_seconds||90;maxTokens.value=c.max_tokens||700;idleTimeout.value=c.session?.idle_timeout_minutes||20;absoluteTimeout.value=c.session?.absolute_timeout_minutes||60;persist.checked=!!c.privacy?.persist_student_chats;adaptiveEnabled.checked=c.adaptive_learning?.enabled!==false;sessionOnly.checked=true}
async function saveAdmin(){if(persist.checked){persist.checked=false;return alert('Elevsamtaler er fail-closed i v0.4 og kan ikke aktiveres.')}let c={school_name:schoolName.value,model:model.value,api_url:apiUrl.value,auth_mode:authMode.value,api_key_env:apiKeyEnv.value,request_timeout_seconds:+timeout.value,max_tokens:+maxTokens.value,privacy:{persist_student_chats:false,retention_days:0},adaptive_learning:{enabled:adaptiveEnabled.checked,session_only:true},session:{idle_timeout_minutes:+idleTimeout.value,absolute_timeout_minutes:+absoluteTimeout.value}};await req('/api/admin/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});adminResult.innerHTML='<p class="good">Konfiguration gemt.</p>'}
async function testBackend(){adminResult.textContent='Tester…';try{let j=await req('/api/admin/test',{method:'POST'});adminResult.innerHTML='<p class="'+(j.ok?'good':'bad')+'">'+esc(j.reply)+'</p>'}catch(e){adminResult.innerHTML='<p class="bad">'+esc(e.message)+'</p>'}}
window.addEventListener('pagehide',()=>{if(sid&&navigator.sendBeacon){navigator.sendBeacon('/api/session/end',new Blob([JSON.stringify({session_id:sid})],{type:'application/json'}));}});
boot().catch(e=>document.body.innerHTML='<pre>'+esc(e.message)+'</pre>');
</script></body></html>'''
